[profile.release]
panic = 'unwind'

[workspace]
resolver = "2"

members = [
    'node',
    'runtime',
    'multi-pow',
    'modified-sp-consensus-pow',
    'modified-sc-consensus-pow',
]

exclude = [
    "contracts/roulette",
    "contracts/psp22-traits",
    "contracts/psp22",
    "contracts/simple-dex",
]