[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'runtime',
    'node/sha3pow',
]

exclude = [
    "academy-pow-extension",
    "contracts/roulette",
    "contracts/psp22-traits",
    "contracts/psp22",
    "contracts/simple-dex",
]