[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'runtime',
    'node/sha3pow',
    'account',
]

exclude = [
    "contracts/roulette",
    "contracts/psp22-traits",
    "contracts/psp22",
    "contracts/simple-dex",
    "contracts/old_a",
    "contracts/new_a",
    "contracts/test-utils",
]