[profile.release]
panic = 'unwind'

[workspace]
resolver = "2"
members = [
    'node',
    'runtime',
    'node/sha3pow',
    'account',
]
exclude = [
    "contracts/roulette",
    "contracts/psp22-traits",
    "contracts/psp22",
    "contracts/simple-dex",
]

[workspace.dependencies]
futures = '0.3.1'
log = '0.4.8'
clap = { version = "4.3.0", features = ["derive"] }
parity-scale-codec = '3.1.2'
scale-info = "2.8.0"
sha3 = "0.10.1"
rand = { version = "0.8.5", features = ["small_rng"] }
hex-literal = "0.4.1"
hex = "0.4"
async-trait = "0.1.68"
serde = "1.0.164"
blake2-rfc = "0.2.18"
impl-serde = "0.4.0"
libsecp256k1 = "0.7.1"

sha3pow = {path = './sha3pow'}
account = { path = "../account" }

# These dependencies are used for the node template's RPCs
jsonrpsee = { version = "0.16.0", features = ["server"] }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }

sc-consensus-pow = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-consensus-manual-seal = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-basic-authorship = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-cli = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-client-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-consensus = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-executor = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-network = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-network-sync = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-rpc = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-service = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-telemetry = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-transaction-pool = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sc-transaction-pool-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-blockchain = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-consensus = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-consensus-pow = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-core = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-inherents = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-runtime-interface = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-io = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-session = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-std = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-version = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
substrate-wasm-builder = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-offchain = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-keystore = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-timestamp = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
sp-transaction-pool = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
frame-executive = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
frame-support = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
frame-system = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
frame-system-rpc-runtime-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-balances = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-timestamp = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-contracts = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-contracts-primitives = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-insecure-randomness-collective-flip = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-transaction-payment = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
pallet-transaction-payment-rpc-runtime-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }
fc-consensus = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
fc-db = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
fc-mapping-sync = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
fc-rpc = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
fc-rpc-core = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
fc-storage = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
fp-rpc = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
fp-evm = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
fp-self-contained = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
pallet-ethereum = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
pallet-evm = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
pallet-evm-chain-id = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
pallet-evm-precompile-modexp = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
pallet-evm-precompile-sha3fips = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
pallet-evm-precompile-simple = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }
pallet-base-fee = {git = "https://github.com/paritytech/frontier.git", branch = "bar/polkadot-v0.9.42" }


substrate-build-script-utils  = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.42" }