version: "3.7"

services:
  visualizer:
    build: .
    container_name: visualizer
    restart: always
    ports:
      - "3000:3000"

  first_node:
    image: ghcr.io/polkadot-blockchain-academy/academy-pow:main
    container_name: first_node
    restart: always
    ports:
      - "9944:9944"
    command: [
      "--dev",
      "--mining-algo=keccak",
      "--rpc-external",
      "--name=firstnode",
      "--node-key=0xf50eb51c7941cfe177b28f0c3a2b1261d579bc1a0c30f7ee112415c544adc0ae"
    ]

  # NOTE: uncomment this to use a multi node network
  #       this will require more memory (about 8gb per node)
  # second_node:
  #   image: ghcr.io/polkadot-blockchain-academy/academy-pow:main
  #   container_name: second_node
  #   restart: always
  #   ports:
  #     - "8844:9944"
  #   command: [
  #     "--dev",
  #     "--mining-algo=keccak",
  #     "--rpc-external",
  #     "--bootnodes=/dns/first_node/tcp/30333/p2p/12D3KooWMQwdmPwsWNWUJhMNyQE4QzcCivxr7DDhhB3E46xH3QLx"
  #   ]

  # NOTE: uncomment this to use a multi node network
  #       this will require more memory (about 8gb per node)
  # third_node:
  #   image: ghcr.io/polkadot-blockchain-academy/academy-pow:main
  #   container_name: third_node
  #   restart: always
  #   ports:
  #     - "7744:9944"
  #   command: [
  #     "--dev",
  #     "--mining-algo=md5",
  #     "--rpc-external",
  #     "--bootnodes=/dns/first_node/tcp/30333/p2p/12D3KooWMQwdmPwsWNWUJhMNyQE4QzcCivxr7DDhhB3E46xH3QLx"
  #   ]
  #   depends_on:
  #     - first_node

  # NOTE: uncomment this to use a multi node network
  #       this will require more memory (about 8gb per node)
  # forth_node:
  #   image: ghcr.io/polkadot-blockchain-academy/academy-pow:main
  #   container_name: forth_node
  #   restart: always
  #   ports:
  #     - "6644:9944"
  #   command: [
  #     "--dev",
  #     "--mining-algo=sha3",
  #     "--rpc-external",
  #     "--bootnodes=/dns/first_node/tcp/30333/p2p/12D3KooWMQwdmPwsWNWUJhMNyQE4QzcCivxr7DDhhB3E46xH3QLx"
  #   ]
  #   depends_on:
  #     - first_node

