[package]
authors = ['Anonymous']
edition = '2021'
name = 'sha3pow'
version = '3.0.0'

[dependencies]
parity-scale-codec = '3.1.2'
sha3 = "0.10.1"
rand = { version = "0.8.5", features = ["small_rng"] }

sc-consensus = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sc-consensus-pow = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sc-client-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sp-api = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sp-blockchain = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sp-consensus-pow = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sp-core = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
sp-runtime = {git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.43" }
