---
name: Contracts unit tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    paths:
      - contracts/**

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  basic-checks:
    name: Check contracts code
    runs-on: ubuntu-latest
    env:
      CARGO_CONTRACT_VERSION: 3.0.1
      RUST_CONTRACTS_TOOLCHAIN: nightly-2023-01-10-x86_64-unknown-linux-gnu
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install prerequisites
        run: |
          rustup toolchain install ${RUST_CONTRACTS_TOOLCHAIN}
          rustup component add rust-src --toolchain ${RUST_CONTRACTS_TOOLCHAIN}

          mkdir -p /tmp/$RUST_CONTRACTS_TOOLCHAIN/

          export WASM_BUILD_WORKSPACE_HINT=${PWD}
          export CARGO_TARGET_DIR=/tmp/$RUST_CONTRACTS_TOOLCHAIN/target/

          cargo +${RUST_CONTRACTS_TOOLCHAIN} install cargo-dylint dylint-link

          cargo +${RUST_CONTRACTS_TOOLCHAIN} install --version $CARGO_CONTRACT_VERSION \
            --force --locked cargo-contract

      - name: Check excluded packages
        run: |
          ./scripts/check_excluded.sh
